config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'toggle', to: 'application#toggle_theme'
  patch "positions/:id/move", to: "positions#move"

  resources :notes


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  acts_as_list scope: :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, -> { order(position: :asc) }, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:set_theme, :toggle_theme]

  def set_theme
    cookies[:theme] = 'light'
  end

  def toggle_theme
    theme = cookies[:theme]
    cookies[:theme] = theme == 'light' ? 'dark' : 'light'
    p controller_path
    p request.referrer
    p '***************'
    if request.referrer.match(/users/)
      redirect_to(request.referrer)
    else
      redirect_to(request.referrer)
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[edit update destroy]

  def index
    @notes = current_user.notes.order(:created_at)
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user = current_user
    if @note.save
      redirect_to notes_path
    else
      flash[:alert] = 'Note could not be created'
      render :new
    end
  end

  def edit
  end

  def update
    @note.update(note_params)
    if @note.save
      render @note
    else
      flash[:alert] = 'Note could not be updated'
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def move
    @item = params[:klass].constantize.find(params[:id])
    @item.insert_at(params[:position].to_i)
    head :ok
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
  super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, session: [:last_visited_path])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
      root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   if session[:last_visited_path].present?
  #     session[:last_visited_path]
  #   else
  #     root_path
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dark?
    cookies[:theme] == 'dark'
  end

  def dark_class?
    dark? ? 'dark' : nil
  end

  def btn_dark?(outline: false)
    if outline
      "btn btn-outline-#{dark? ? 'warning' : 'primary'}"
    else
      "btn btn-#{dark? ? 'warning' : 'primary'}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= yield :head %>
    <%#= turbo_include_tags %>
    <%#= stimulus_include_tags %>
  </head>
  <body class="<%= dark_class? %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <div class="row align-items-center justify-content-center <%= 'home-container' unless controller_name == 'notes' %>">
        <div class="col-<%= controller_path.match(/devise/) ? '5' : '10' %> my-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for @note do |f| %>
  <%= f.input :content, label: false, value: @note.content, input_html: { rows: 4 } %>
  <%= f.submit "Save note", class: "btn #{dark? ? 'btn-light' : 'btn-primary'} btn-sm" %>
<% end %>

app/views/notes/_note.html.erb
<div class="col-3" data-target="drag-and-drop.id" data-id="<%= note.id %>" data-klass="<%= note.class %>">
  <div class="note-card <%= dark_class? %>">
    <i class="fas fa-grip-vertical"></i>
    <%= turbo_frame_tag "edit_note" do %>
      <%= link_to edit_note_path(note) do %>
        <p><%= note.content %></p>
      <% end %>
    <% end %>
    <%= link_to note_path(note), method: :delete do %>
      <span><i class="fas fa-times"></i></span>
    <% end %>
  </div>
</div>

app/views/notes/edit.html.erb
<%= turbo_frame_tag "edit_note", target: '_top' do %>
  <%= render 'form', note: @note %>
<% end %>

app/views/notes/index.html.erb
<div class="container">
  <%= turbo_frame_tag 'notes' do %>
    <% if @notes.empty? %>
      <p class='text-center'>You don't have any notes yet. Go ahead and add your first one!</p>
    <% end %>
    <div class="row" data-target="note.list" data-controller="drag-and-drop" data-drag-url="/positions/:id/move">
      <% @notes.each do |note| %>
        <%= render 'note', note: note %>
      <% end %>
      <div class="col-3">
        <div class="new-note-card">
          <%= turbo_frame_tag "new_note", src: new_note_path(@note), target: '_top' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/notes/new.html.erb
<%= turbo_frame_tag "new_note", target: '_top' do %>
  <%= render 'form', note: @note %>
<% end %>

app/views/pages/home.html.erb
<div class="text-center">
  <h1>Write down your thoughts</h1>
  <% if !current_user %>
    <p>Welcome! Please <%= link_to 'login', new_user_session_path %> or <%= link_to 'sign up', new_user_registration_path %> to start taking notes!</p>
  <% elsif current_user && current_user.notes != [] %>
    <p>Welcome back! You have <%= link_to "#{current_user.notes.count} notes", notes_path %> waiting for you!</p>
  <% else %>
    <p>Welcome! You don't have any notes yet. Go ahead and add your first one!</p>
    <%= link_to 'My notes', notes_path %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon <%= dark? ? 'navbar-dark bg-dark' : 'navbar-light bg-white' %>">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "paper.svg" %>
    <span>Sticky noted</span>
    <%= @dark %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse <%= dark_class? %>" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to toggle_path, class: "#{dark? ? 'btn btn-outline-light' : 'btn btn-outline-dark'} ml-3" do %>
          <% if dark? %>
            <i class="fas fa-sun pr-1"></i>Light mode
          <% else %>
            <i class="fas fa-moon pr-1"></i>Dark mode
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</div>